import { useEffect, useRef, useState } from 'react'
import { useSchoolDemo } from '../demo/DemoContext.jsx'
import { scopeLabel } from '../demo/schoolDemo.js'
import FileImport from './FileImport.jsx'

export default function AccountDemoDialog({page,onClose}) {
  const {state,execute,isDemo,session,findStudents,onLogout,changePassword}=useSchoolDemo()
  const dialog=useRef(null)
  const [feedback,setFeedback]=useState(''),[query,setQuery]=useState(''),[queryBy,setQueryBy]=useState('studentNumber'),[results,setResults]=useState([]),[searching,setSearching]=useState(false),[logo,setLogo]=useState(null)
  useEffect(()=>{dialog.current.showModal()},[])
  async function save(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));try{await execute('profile','PATCH',{version:state.profile.version,schoolName:f.schoolName,schoolAddress:f.schoolAddress.split('\n').map(s=>s.trim()).filter(Boolean)});setFeedback('学校资料已保存。')}catch(e){setFeedback(e.message)}}
  async function uploadLogo(){try{await execute('profile','POST',{action:'upload_logo',version:state.profile.version,file:isDemo?{name:logo.file.name,size:logo.file.size}:logo.file,...(isDemo?{logoData:logo.dataURL}:{})});setFeedback('Logo 已更新。');setLogo(null)}catch(e){setFeedback(e.message)}}
  async function password(e){e.preventDefault();const form=e.currentTarget,f=Object.fromEntries(new FormData(form));const length=new TextEncoder().encode(f.newPassword).length;if(length<12||length>72||f.newPassword!==f.confirm){setFeedback('新密码需为 12–72 字节，两次输入需一致。');return}try{await changePassword({currentPassword:f.currentPassword,newPassword:f.newPassword});form.reset();setFeedback(isDemo?'已演示改密流程；未保存或修改密码。':'密码已更新，请重新登录。')}catch(e){setFeedback(e.message)}}
  async function search(){setSearching(true);setResults([]);try{setResults(await findStudents(query,queryBy));setFeedback('')}catch(e){setFeedback(e.message)}finally{setSearching(false)}}
  return <dialog ref={dialog} className="demo-dialog" onCancel={onClose} onClick={e=>{if(e.target===dialog.current)onClose()}}><div className="demo-dialog-inner">
    <div className="section-title"><h2>{page==='profile'?'学校资料':page==='directory'?'校区与学生':'账号设置'}</h2><button className="quiet-action" onClick={onClose} aria-label="关闭账号窗口">关闭</button></div>
    <p className="demo-callout">{isDemo?'本地演示 · 修改仅在本次登录中保留。':'已连接学校管理服务。修改会保存到服务器。'}</p>
    {page==='profile'&&<><form className="form-grid" onSubmit={save}><label className="full-row">学校名称<input name="schoolName" defaultValue={state.profile.schoolName} maxLength={100} required /></label><label className="full-row">地址（每行一段）<textarea name="schoolAddress" defaultValue={state.profile.schoolAddress.join('\n')} required rows={3} /></label><button type="submit" className="primary-action">保存资料</button></form><FileImport kind="logo" label="选择学校 Logo" onReady={setLogo} onClear={()=>setLogo(null)} preview={result=><img className="demo-logo-preview" src={result.dataURL} alt="待上传 Logo 预览" />} />{logo&&<button type="button" className="primary-action" onClick={uploadLogo}>上传 Logo</button>}{state.profile.schoolLogo&&<img className="demo-logo-preview" src={state.profile.schoolLogo} alt="当前学校 Logo" />}</>}
    {page==='directory'&&<><h3>班级目录</h3><div className="demo-record-list">{state.directory.classes.map(s=><div key={`${s.compoundID}/${s.departmentID}/${s.classID}`}><strong>{scopeLabel(s,state.directory)}</strong></div>)}</div><label className="demo-select-label">查询方式<select value={queryBy} onChange={e=>{setQueryBy(e.target.value);setResults([])}}><option value="studentNumber">完整学号</option><option value="name">姓名</option></select></label><label className="demo-select-label">查找学生<input placeholder="输入查询内容" value={query} onChange={e=>{setQuery(e.target.value);setResults([])}} /></label><button className="quiet-action" disabled={searching||!query} onClick={search}>{searching?'正在查询…':'查找学生'}</button><div className="demo-record-list">{results.map(s=><div key={s.studentID}><div><strong>{s.studentName} · {s.studentNumber||'未填写学号'}</strong><small>{scopeLabel(s,state.directory)}</small></div></div>)}</div></>}
    {page==='account'&&<><dl className="review-facts"><div><dt>登录账号</dt><dd>{session?.admin?.loginName||'admin'}</dd></div><div><dt>会话</dt><dd>{isDemo?'本地演示':session?.expiresAt?`有效至 ${session.expiresAt.replace('T',' ').slice(0,19)}`:'学校管理会话'}</dd></div></dl><p>账号由平台开通。修改密码会撤销该管理员的全部会话。</p><details><summary>{isDemo?'修改密码流程演示':'修改密码'}</summary><form className="form-grid" onSubmit={password}>{isDemo&&<p className="full-row demo-callout">请使用虚构内容演示。</p>}<label className="full-row">当前密码<input name="currentPassword" type="password" required autoComplete="current-password" /></label><label className="full-row">新密码<input name="newPassword" type="password" required autoComplete="new-password" /></label><label className="full-row">确认新密码<input name="confirm" type="password" required autoComplete="new-password" /></label><button className="primary-action" type="submit">{isDemo?'演示修改':'保存新密码并退出'}</button></form></details></>}
    {feedback&&<p role="status">{feedback}</p>}{page==='account'&&<button type="button" className="quiet-action" onClick={onLogout}>退出登录</button>}
  </div></dialog>
}
